# Generated by Django 6.1.1 on 2026-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="is_supervisor",
            field=models.BooleanField(default=False, verbose_name="Is Supervisor"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_supplier",
            field=models.BooleanField(default=True, verbose_name="Is Supplier"),
        ),
    ]
