# Generated by Django 6.1.1 on 2026-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_alter_user_is_supervisor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_supervisor",
            field=models.BooleanField(default=False, verbose_name="Es Supervisor"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_supplier",
            field=models.BooleanField(default=True, verbose_name="Es Proveedor"),
        ),
    ]
