# Generated by Django 6.1.1 on 2026-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_is_supervisor_alter_user_is_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dirección (Opcional)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=0, max_length=20, verbose_name="Número de Teléfono"
            ),
            preserve_default=False,
        ),
    ]
