# Generated by Django 6.1.1 on 2026-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("COMPRAS", "Compras"),
                    ("ADMINISTRACION", "Administración"),
                    ("INGENIERIA", "Ingeniería"),
                    ("TOPOGRAFIA", "Topografía"),
                    ("CONTROL_CALIDAD", "Control de Calidad"),
                    ("LOGISTICA", "Logística"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("SEGURIDAD_HIGIENE", "Seguridad e Higiene"),
                ],
                default="Sin categoría",
                max_length=50,
                verbose_name="Categoría / Departamento",
            ),
        ),
    ]
