# Generated by Django 6.1.1 on 2026-10-01 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notes/attachments/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                        ],
                        message="Solo se permiten archivos: JPG, PNG, PDF, Word y Excel",
                    )
                ],
                verbose_name="Archivo adjunto",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("COMPRAS", "Compras"),
                    ("ADMINISTRACION", "Administración"),
                    ("INGENIERIA", "Ingeniería"),
                    ("TOPOGRAFIA", "Topografía"),
                    ("CONTROL_CALIDAD", "Control de Calidad"),
                    ("LOGISTICA", "Logística"),
                    ("RECURSOS_HUMANOS", "Recursos Humanos"),
                    ("SEGURIDAD_HIGIENE", "Seguridad e Higiene"),
                ],
                default="COMPRAS",
                max_length=50,
                verbose_name="Categoría / Departamento",
            ),
        ),
    ]
