# Generated by Django 6.1.1 on 2026-10-01 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_attachment_alter_note_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="attachment",
        ),
        migrations.CreateModel(
            name="NoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="notes/attachments/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ],
                                message="Solo se permiten archivos: JPG, PNG, PDF, Word y Excel",
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="notes.note",
                    ),
                ),
            ],
        ),
    ]
